services:

  bpmn_assistant:
    build:
      context: .
      dockerfile: ./src/bpmn_assistant/Dockerfile
    image: sithuyehtun/bpmn_assistant:latest
    ports:
        - "8000:8000"
    env_file:
      - ./src/bpmn_assistant/.env
    networks:
      - bpmn-network

networks:
  bpmn-network:
    driver: bridge
